"""empty message

Revision ID: 609fe25e8a32
Revises: 54461f87d8a6
Create Date: 2022-04-03 21:09:20.060202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609fe25e8a32'
down_revision = '54461f87d8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_item_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_unique_constraint('cart_item_key', ['item'])

    # ### end Alembic commands ###
